### PR TITLE
Add attestation by svanstaa for 27.1 codesigned and non-codesigned

### PR DESCRIPTION
**Pull request by svanstaa**

### CODE REVIEW

**Comment by achow101** [comment]
```
5d4
< 06bf5d34aef01f21dac88708efa32d5e673c3ce1c8f17b1ca34b0e517ed8e43f  bitcoin-27.1-arm64-apple-darwin.zip
9c8
< bce6f981c198c616dcedd802bfda7693ec5a8a04aa57804edfad94305f7796b0  bitcoin-27.1-codesignatures-27.1.tar.gz
---
> 6ff2f9553de1f549c58e5969edae6d1c6d39d580cd6d1c59eced82e0f1a5aa4d  bitcoin-27.1-codesignatures-c861fcad1151.tar.gz
17d15
< 25445080e2616d7c621f48f51e7a4294698d92016ef27ab88608cbe824f93364  bitcoin-27.1-x86_64-apple-darwin.zip
ERR: The SHA256SUMS attestation in these two directories differ:
    '/home/ava/bitcoin/guix.sigs//27.1/achow101/all.SHA256SUMS'
    '/home/ava/bitcoin/guix.sigs//27.1/svanstaa/all.SHA256SUMS'
```

Looks like you're missing MacOS codesigned, the codesignatures.tar.gz is not the tag.

**Comment by 0xB10C** [comment]
fwiw:

`all.SHA256SUMS` summary for release `27.1`
```
User (see mapping below)            a b c d e f g h
aarch64-linux-gnu-debug.tar.gz      █ █ █ █ █ █ █ █
aarch64-linux-gnu.tar.gz            █ █ █ █ █ █ █ █
arm-linux-gnueabihf-debug.tar.gz    █ █ █ █ █ █ █ █
arm-linux-gnueabihf.tar.gz          █ █ █ █ █ █ █ █
arm64-apple-darwin-unsigned.tar.gz  █ █ █ █ █ █ █ █
arm64-apple-darwin-unsigned.zip     █ █ █ █ █ █ █ █
arm64-apple-darwin.tar.gz           █ █ █ █ █ █ █ █
arm64-apple-darwin.zip              █ █ █ █ █ X █ █
codesignatures-27.1.tar.gz          █ █ █ █ █ X █ █
codesignatures-c861fcad1151.tar.gz  X X X X X █ X X
powerpc64-linux-gnu-debug.tar.gz    █ █ █ █ █ █ █ █
powerpc64-linux-gnu.tar.gz          █ █ █ █ █ █ █ █
powerpc64le-linux-gnu-debug.tar.gz  █ █ █ █ █ █ █ █
powerpc64le-linux-gnu.tar.gz        █ █ █ █ █ █ █ █
riscv64-linux-gnu-debug.tar.gz      █ █ █ █ █ █ █ █
riscv64-linux-gnu.tar.gz            █ █ █ █ █ █ █ █
win64-debug.zip                     █ █ █ █ █ █ █ █
win64-setup-unsigned.exe            █ █ █ █ █ █ █ █
win64-setup.exe                     █ █ █ █ █ █ █ █
win64-unsigned.tar.gz               █ █ █ █ █ █ █ █
win64.zip                           █ █ █ █ █ █ █ █
x86_64-apple-darwin-unsigned.tar.gz █ █ █ █ █ █ █ █
x86_64-apple-darwin-unsigned.zip    █ █ █ █ █ █ █ █
x86_64-apple-darwin.tar.gz          █ █ █ █ █ █ █ █
x86_64-apple-darwin.zip             █ █ █ █ █ X █ █
x86_64-linux-gnu-debug.tar.gz       █ █ █ █ █ █ █ █
x86_64-linux-gnu.tar.gz             █ █ █ █ █ █ █ █
bitcoin-27.1.tar.gz                 █ █ █ █ █ █ █ █
```

<details><summary>Details</summary>
Symbols:

- all hashes match: `█`
- missing hash: `X`
- hash mismatch: one of `◆`, `▞`, `▄`, `▀`, `▌`, `▐`, `▚`

Username mapping:
- a: guggero
- b: achow101
- c: kvaciral
- d: TheCharlatan
- e: fanquake
- f: svanstaa
- g: glozow
- h: m3dwards

</details>

**Comment by glozow** [comment]
It looks like an extra hash for something that isn't 27.1 - everyone else is correct to not have it.

**Comment by svanstaa** [comment]
Dang!

Gloria Zhao ***@***.***> schrieb am Mo., 17. Juni 2024, 18:33:

**Comment by achow101** [comment]
> what ist the codesignatures-c861fcad1151.tar.gz for?

It's an archive of https://github.com/bitcoin-core/bitcoin-detached-sigs at c861fcad1151.

The issue is that c861fcad1151 is not the tagged commit and is missing the detached signature for MacOS. Hence your build is missing the MacOS codesigned binaries (`arm64-apple-darwin.zip` and `x86_64-apple-darwin.zip`)

**Comment by 0xB10C** [comment]
> @0xB10C where do I get the fancy ASCII table generator? Would be a nice addition for guix-verify.

I added it in https://github.com/bitcoin-core/guix.sigs/pull/1207 alongside a CI job that's supposed to comment the summary on each PR (the CI task that's currently failing..) and hope to fix it with https://github.com/bitcoin-core/guix.sigs/pull/1263.

**Pull request merged**
