### PR TITLE
drop: 0xb10c 27.0rc1 & 25.2rc2 (hash mismatch)

### PR DESCRIPTION
**Pull request by 0xB10C**
Similar to #1197, this drops my recent SHA256SUMS as they don't match the others. I recently switched to a new GUIX build setup, which I think is the cause for this mismatch.

Affected are:

- 27.0 (added #1194; removed #1197)
- 27.0rc1 (added #1169; removed here)
- 25.2rc2 (added #1170; removed here)

See also: https://github.com/bitcoin-core/guix.sigs/commits?author=0xB10C

### CODE REVIEW

**Comment by hebasto** [comment]
> I recently switched to a new GUIX build setup...

Mind providing its description or steps to reproduce it?

**Comment by hebasto** [comment]
Might be related to https://github.com/bitcoin/bitcoin/issues/29754, which implies not 100% isolated build environment.

**Comment by laanwj** [comment]
Looking at the 27.0 output, curiously, these two files are the same as the others:
```
 9c1ee651d3b157baccc3388be28b8cf3bfcefcd2493b943725ad6040ca6b146b  bitcoin-27.0.tar.gz
 e8114ed85a976ff439bd78cbf026e3f9bfafdf40d0fe75121e73bd4b7af347a4  bitcoin-27.0-win64-setup-unsigned.exe
```
The others all diverge. 

i can understand about the source tarball, but that win64 also matches (but not any of the others) is... strange.

> I've re-triggered a 27.0 build with this setup to then compare binaries.

Would imagine they all differ in a similar way. so for comarison it'd be enough to upload say, x86_64 linux and maybe the associated -debug (if we need to go that deep to compare symbol addresses).

**Comment by laanwj** [comment]
i've been able to reproduce @0xB10C's results:
```
[nix-shell:/data/build/bitcoin/guix-build-27.0/output/x86_64-linux-gnu]$ sha256sum *
30bcdcff385ce2f790613e499a2cde0b66aee082c1053bdc619723a553601d87  bitcoin-27.0-x86_64-linux-gnu-debug.tar.gz
9ddf93c4548cb0fa14a687dc131685eb54611a7e4d99626cc4f319b54f3cfc46  bitcoin-27.0-x86_64-linux-gnu.tar.gz
```
Will compare them to the release.

**Comment by laanwj** [comment]
In `contrib/guix/libexec/build.sh` we do the following to deterministically set the dates for created archives to a specific epoch

For tar, pass `--mtime` option through the default options environment variable `TAR_OPTIONS`:
```
export TAR_OPTIONS="--owner=0 --group=0 --numeric-owner --mtime='@${SOURCE_DATE_EPOCH}' --sort=name"                                                                                                                                       
```

For zip (windows), use touch to set the date before compressing using `zip`:
```
                find "${DISTNAME}" -not -name "*.dbg" -print0 \
                    | xargs -0r touch --no-dereference --date="@${SOURCE_DATE_EPOCH}"
```
Both don't work inside Nix Guix, somehow they get squashed to `1981`.

**Comment by laanwj** [comment]
@0xB10C i think i solved it, just do
```bash
unset SOURCE_DATE_EPOCH
contrib/guix/guix-build
```
(we likely want to do this inside the build script, but this will work for now)

**Comment by 0xB10C** [comment]
Wow @laanwj good detective work! I can confirm that the files in the tar.gz archives are set to 1980-01-01 and hash to the same (incorrect) hash. I've `unset SOURCE_DATE_EPOCH` and am doing another 27.0 GUIX build now.

**Comment by 0xB10C** [comment]
Does it make sense to have a CI job that errors in cases where newly added hashes don't match the existing hashes for the same release?

**Comment by 0xB10C** [comment]
> We do need some kind of warning system though if there are diverging outputs in the first place. If they go undetected it's also pointless 😄
> 
> But it shouldn't ideally prevent merging.

A nightly CI job on `main` that opens an issue if there's a mismatch?

**Comment by laanwj** [comment]
> A nightly CI job on main that opens an issue if there's a mismatch?

That could work! In any case, it'd make sense to open a new issue in this repository for discussing this.

**Pull request merged**
