### PR TITLE
change svanstaa builder keys

### PR DESCRIPTION
**Pull request by svanstaa**

### CODE REVIEW

**Comment by laanwj** [comment]
Old key:
```
pub   rsa3072/0x476E74C8529A9006 2020-08-03 [SC] [expired: 2024-11-23]
      9ED99C7A355AE46098103E74476E74C8529A9006
uid                             Sebastian van Staa <sebastian.van.staa@...>
sub   rsa3072/0xFF5C9E3F8ACAF77A 2020-08-03 [E] [expired: 2021-08-03]
sub   rsa3072/0xB14CC9F833238F85 2022-11-24 [S] [expired: 2024-11-23]
```
New key:
```
pub   rsa4096/0xCFB2C83C66CD792A 2024-12-06 [SC]
      33C103B4B2794170546CCF7BCFB2C83C66CD792A
uid                             Sebastian van Staa <svanstaa@...>
sub   rsa4096/0x96C5C1011B8563FD 2024-12-06 [E]
```

**Comment by svanstaa** [comment]
Thanks, that is correct. What needs to be done to merge my updated keys?

Am Sa., 7. Dez. 2024 um 16:16 Uhr schrieb laanwj ***@***.***>:

**Comment by laanwj** [comment]
i left it open so that some other people can see it before merge, in case there's something wrong

**Comment by svanstaa** [comment]
Ok, I see. Take your time. Safety first.

laanwj ***@***.***> schrieb am So., 8. Dez. 2024, 11:54:

**Pull request closed without merging**
