### PR TITLE
Add luke-jr Guix attestations for 21.99-guixtest1 non-codesigned

### PR DESCRIPTION
**Pull request by luke-jr**
Produced using guix gitian descriptors in 5fa449450198d85670991a4ea0afde1cb39d2e15 (third-party binaries used for build)

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Can be closed?

**Comment by laanwj** [comment]
Well, or merge. Depends on whether we're going to get rid of the -guixtest directory or keep it.

**Comment by MarcoFalke** [comment]
The folder has a different format, so can't be checked even. I'd say to remove everything to avoid confusion.

**Comment by laanwj** [comment]
SGTM

**Pull request closed without merging**
