### PR TITLE
27.1_all

### PR DESCRIPTION
**Pull request by willcl-ark**

### CODE REVIEW

**Comment by 0xB10C** [comment]
```
Run git diff --no-commit-id --name-only a6bb2ded2069844a0f21f3a17a55e11dcc7f1f40..ffa4d9d2535e48d73c3f949046736cd7049b1a37
26.2rc1/Sjors/all.SHA256SUMS
26.2rc1/Sjors/all.SHA256SUMS.asc
26.2rc1/Sjors/noncodesigned.SHA256SUMS
26.2rc1/Sjors/noncodesigned.SHA256SUMS.asc
27.1/luke-jr/all.SHA256SUMS.asc
27.1/luke-jr/noncodesigned.SHA256SUMS.asc
27.1/willcl-ark/all.SHA256SUMS
27.1/willcl-ark/all.SHA256SUMS.asc
27.1/willcl-ark/noncodesigned.SHA256SUMS
27.1/willcl-ark/noncodesigned.SHA256SUMS.asc
```

Hm yeah it's showing `26.0rc1` too as it isn't comparing against `main HEAD` but rather https://github.com/bitcoin-core/guix.sigs/commit/b0ed21070b34cd8e750616cefffd90e06554738c (which isn't `main HEAD` anymore). At least commenting is now working...

**Comment by achow101** [comment]
#1272 fixes the issue with `git diff`.

**Comment by fanquake** [comment]
This is looking better now.

**Comment by fanquake** [comment]
Even better now. lgtm

**Pull request merged**
