### PR TITLE
Add attestations by jackielove4u for 23.0rc1 non-codesigned

### PR DESCRIPTION
**Pull request by gruve-p**

### CODE REVIEW

**Comment by achow101** [comment]
Hmm. The signature appears to be invalid.

**Comment by gruve-p** [comment]
Thats odd, works fine here. Do you need my public key ?

**Comment by gruve-p** [comment]
Not sure why it appears to be invalid. I will sign it again and send another PR.

**Comment by achow101** [comment]
I was able to get the key from keyservers. The signature is just invalid.

```
gpg: Signature made Sat Mar  5 03:55:30 2022 EST
gpg:                using RSA key 287AE4CA1187C68C08B49CB2D11BD4F33F1DB499
gpg: BAD signature from "jackielove4u <jackielove4u@hotmail.com>" [unknown]
ERR: Failed to verify GPG signature in '/home/andy/bitcoin/guix.sigs//23.0rc1/jackielove4u/noncodesigned.SHA256SUMS'
```

**Comment by gruve-p** [comment]
Followed up with a new PR: https://github.com/bitcoin-core/guix.sigs/pull/150

**Pull request merged**
